name: On Push

on:
  push:
    branches:
      - master

jobs:

  build:

    if: github.repository == 'MrFSP/backend-project-lvl2'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: npm install
      run: npm run build --if-present
      run: npm test
